baseURL = "/"
languageCode = "en-us"
title = "Tiny Human House"
theme = "purehugo"
Paginate = 5

[params]
  twitterName = "mdgee"
  githubName = "meshellg"
  description = "Learning and Growing Together."
