baseURL = "/"
languageCode = "en-us"
title = "Tiny Human House"
theme = "purehugo"
Paginate = 10
disqusShortname = "xxxx"

[params]
  twitterName = "mdgee"
  githubName = "meshellg"
  description = "mom blog for moms"
  google_analytics = "UA-xxxxxx-xx"
